#!/usr/bin/php

<?php

define('DAYS_RECENT', 7);
define('LONG_LINE', 5000);
define('LONG_PATTERN', 30);

// Whether to apply lax or strict check rules. Lax rules are less reliable.
define('USE_STRICT', FALSE);

print 'aScan Code Scanner, updated 06 September 2022.' . "\n\n";
main();

/**
 * Main function.
 */
function main() {
  search_delete_hostgator_suspected();
  $extensions = ['php', 'inc', 'theme', 'module'];

  // Load signatures depending on strictness.
  $signatures = get_strict();
  if (!USE_STRICT) {
    $signatures += get_lax();
  }

  printf("\rListing the files.");
  $files = find_files($extensions);
  $count = count($files) > 0 ? count($files) : 'no';
  printf("\rFound %s files to scan.", $count);
  $scan_results = [];
  $total = count($files);
  $i = 0;
  foreach ($files as $path) {
    $i++;
    $action = '';
    print_progress('Scanning:', $i, $total);
    $positives = scan_file($path, $signatures);
    if (!empty($positives)) {

      // Check if file can be deleted.
      if (can_delete($path)) {
        unlink($path);
        $action = 'deleted';
      }

      $scan_results[] = [
        'path' => $path,
        'positives' => '"' . str_replace('"', '', implode(', ', $positives)) . '"',
        'action' => $action,
      ];
    }
  }

  if (!empty($scan_results)) {
    $file_path = save_positives($scan_results);
    $count = count($scan_results) > 0 ? count($scan_results) : 'no';
    printf("\rScanning complete. \n%s suspicious files found. \nReport saved to %s.", $count, $file_path);
  }
  else {
    printf("\rScanning complete. No threats found.");
  }
  print "\n\n";
}

/**
 * Checks whether the file can be deleted by name.
 *
 * @param string $path
 *   Path to the file.
 *
 * @return bool
 *   Operation result.
 */
function can_delete($path) {
  if (!USE_STRICT) {
    return FALSE;
  }
  $filename = strtolower(pathinfo($path)['filename']);
  $supported_substrings = [
    'content', 'index', 'wpyii2', 'radio', 'about',
  ];
  foreach ($supported_substrings as $substring) {
    if (strpos($filename, $substring) !== FALSE) {
      if (strpos($filename) !== 'index.php') {
        return TRUE;
      }
    }
  }

  return FALSE;
}

/**
 * Save results as a csv file.
 *
 * @param array $results
 *   Ascan scan results.
 *
 * @return string
 *   Saved file path.
 */
function save_positives(array $results) {
  $file_path = getcwd() . '/suspicious.csv';
  $file = fopen($file_path, "w");

  $export = ['File', 'Matches', 'Action'];
  fputcsv($file, $export);
  foreach ($results as $result) {
    $export = [
      str_replace(getcwd() . '/', '', $result['path']),
      $result['positives'],
      $result['action'],
    ];
    fputcsv($file, $export);
  }
  fclose($file);

  return $file_path;
}

/**
 * Scan file for signatures.
 *
 * @param string $path
 *   Path to file.
 * @param array $signatures
 *   Sought signatures.
 *
 * @return array
 *   Array of results.
 */
function scan_file($path, array $signatures) {
  $positives = FALSE;
  $now = time();

  if (file_exists($path)) {
    $file_content = strtolower(file_get_contents($path));
    $positives = [];

    // Check for new and modified files.
    if ($now - filemtime($path) < 3600 * 24 * DAYS_RECENT) {
      #$positives['recent'] = '!RECENT';
    }

    // Scan for signatures.
    foreach ($signatures as $signature) {
      if (strpos($file_content, $signature) !== FALSE) {
        if (strlen($signature) >= LONG_PATTERN) {
          '!LONG_PATTERN(' . strlen($line) . ')';
        }
        else {
          $positives[$signature] = $signature;
        }
      }
    }

    // Scan for long lines.
    if (!USE_STRICT) {
      $lines = explode("\n", $file_content);
      foreach ($lines as $line) {
        if (strlen($line) > LONG_LINE) {
          $positives[$signature] = '!LONG_LINE(' . strlen($line) . ')';
        }
      }
    }
  }

  return $positives;
}

/**
 * Search and delete all hostgator .suspected files.
 */
function search_delete_hostgator_suspected() {
  $files = find_files(['suspected']);
  foreach ($files as $path) {
    unlink($path);
  }

  if (count($files)) {
    print 'Found and deleted ' . count($files) . ' *.suspected files.';
    print 'The fact that there were *.suspected files, means, that the site had likely been hacked.';
  }
}

/**
 * Search for files by extension.
 *
 * @param array $extensions
 *   Extensions to scan for.
 *
 * @return array
 *   Found files.
 */
function find_files(array $extensions = []) {
  $directory = new RecursiveDirectoryIterator(getcwd());
  $iterator = new RecursiveIteratorIterator($directory);
  $files = [];

  foreach ($extensions as $extension) {
    $regex = new RegexIterator($iterator, '/^.+\.' . $extension . '$/i', RecursiveRegexIterator::GET_MATCH);
    foreach ($regex as $item) {
      $files[] = reset($item);
    }
  }

  return $files;
}

/**
 * Progress indicator.
 */
function print_progress($message, $cur, $max) {
  printf("\r%s %6.0f%% (%s/%s)", $message, ($cur / $max) * 100, $cur, $max);
}

/**
 * Returns array of suspicious signatures.
 *
 * @return array
 *   Signatures.
 */
function get_lax() {
  return [
    ']=$',
    ']]=$',
    '=strtolower(',
    '=strtoupper(',
    ');if',
    'basename($_files',
    'ioncube',
    '(base64_decode("',
    '(base64_decode(\'',
    '!@file_exists',
    '@file_put_contents',
    'error_reporting(0)',
    'ignore_user_abort(true)',
    '@header(',
    'window.location',
    '@$',
    ';for',
    ';exit();',
    ').chr(',
    ';public',
    ';private',
    'curl_init();curl_setopt',
    '];$',
    ';function',
  ];
}

/**
 * Returns array of proven signatures.
 *
 * @return array
 *   Signatures.
 */
function get_strict() {
  return [
    '$globals[$globals[\'',
    '=$_cookie;',
    '${"\x',
    'global$',
    '{eval($',
    'eval(base64_decode',
    'eval/*',
    '{eval',
    ')&&$',
    ']as$',
    '$:',
    '$__=s(',
    ',@gzuncompress(',
    'create_function(""',
    'create_function(\'\'',
    'intval(__',
    'eval("\n\$',
    'authedmine',
    ';eval($',
    '){$_',
    ';}return',
    ';}static',
    '){@mkdir(',
    '@unserialize(@',
    '){$_',
    'chr(ord($_',
    'php                                                                           ',
    '$__)',
    ');}function',
    '$_get[\'pumpdie\']',
    '"m"."d"."5"',
    '\'m\'.\'d\'.\'5\'',
    'echo (@$',
    '$ooo',
    '.$OO',
    '@ini_set(\'error',
    'greengoplatform',
    'wpyii2',
    'gzinflate(base64_decode',
  ];
}
